ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
obj-$(CONFIG_HQ_PLATFORM_CAMERA_SUBFLASH) += msm_subflash.o
obj-$(CONFIG_HQ_PLATFORM_CAMERA_FRONTFLASH) += msm_frontflash.o
