#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_GOODIX_TA)	+= goodix_ta/
obj-$(CONFIG_FINGERPRINT_FPC_TEE)	+= fpc_tee/
obj-$(CONFIG_INPUT_FINGERPRINT_GSL6153_ZQL1520) += gsl6153_zql1520/
obj-$(CONFIG_INPUT_FINGERPRINT_GF3258_ZQL1520) += gf3258_zql1520/
obj-$(CONFIG_INPUT_FINGERPRINT_GF3258_ZQL1590) += gf3258_zql1590/
obj-$(CONFIG_INPUT_FINGERPRINT_GSL6153_ZQL1590) += gsl6153_zql1590/
