obj-$(CONFIG_MSM_HOTPLUG)       += msm_hotplug.o
obj-$(CONFIG_INTELLI_PLUG)	+= intelli_plug.o
#obj-$(CONFIG_AUTOSMP)		+= autosmp.o
obj-$(CONFIG_LAZYPLUG)		+= lazyplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG)	+= alucard_hotplug.o
#obj-$(CONFIG_MAKO_HOTPLUG)   += mako_hotplug.o

