ccflags-y += -I$(srctree)/drivers/input/fingerprint/gf3258_zql1520/
obj-$(CONFIG_INPUT_FINGERPRINT_GF3258_ZQL1520) += gf_spi.o
obj-$(CONFIG_INPUT_FINGERPRINT_GF3258_ZQL1520) += netlink.o
obj-$(CONFIG_INPUT_FINGERPRINT_GF3258_ZQL1520) += platform.o
