ccflags-y += -I$(srctree)/drivers/input/fingerprint/gf3258_zql1590/
obj-$(CONFIG_INPUT_FINGERPRINT_GF3258_ZQL1590) += gf_spi.o
obj-$(CONFIG_INPUT_FINGERPRINT_GF3258_ZQL1590) += netlink.o
obj-$(CONFIG_INPUT_FINGERPRINT_GF3258_ZQL1590) += platform.o
