#gt915 touchpanel driver

EXTRA_CFLAGS +=-Wno-error=date-time
EXTRA_CFLAGS +=-Wno-error=unused-function
EXTRA_CFLAGS +=-Wno-date-time

obj-$(CONFIG_TOUCHSCREEN_GT917D_ZQL1590)	+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT917D_ZQL1590)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT917D_ZQL1590)	+= goodix_tool.o
